import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auditore Family - Nova Senha",
  description: "Generated by create next app",
};

export default function NewPassowordRoot({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
