import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auditore Family - Login",
  description: "Generated by create next app",
};

export default function Login({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
