import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auditore Family - Inscreva-se",
  description: "Generated by create next app",
};

export default function Subscribe({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
