import type { Metadata } from "next";
import { Header } from "@/components/header/Header";
import Footer from "../components/Footer";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { AuthProvider } from "@/services/auth";

export const metadata: Metadata = {
  title: "Auditore Family",
  description: "Generated by create next app",
  openGraph: {
    title: "Auditore Family",
    description: "Generated by create next app",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen bg-gray-200 dark:bg-gray-900">
            <AuthProvider>
              <Header />
              {children}
              <Footer />
            </AuthProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
