import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Auditore Family",
  description: "Generated by create next app",
  openGraph: {
    title: "Auditore Family",
    description: "Generated by create next app",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
