import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auditore Family - Verificação no Email",
  description: "Generated by create next app",
};

export default function VerificationRoot({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
