import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auditore Family - Inscrições Antigas",
  description: "Generated by create next app",
};

export default function SubscribeOldRoot({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
