import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auditore Family - perfil de [pessoa]",
  description: "Generated by create next app",
};

export default function OtherProfileRoot({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
