import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auditore Family - Registra-se",
  description: "Generated by create next app",
};

export default function Register({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
